### ISSUE TITLE
Thanks for the package brother :) 

### ISSUE THREAD

**Issue by hemant17** [EmmanuelAyTuz/Views-BS4-Livewire-Datatable#1]
![image](https://user-images.githubusercontent.com/10548023/113039200-07bf0780-91b5-11eb-9bab-c5ef2361aad4.png)
this looks unusual header is missing all over and I think also instead of the table it better to use table-responsive 

using simple 
`<livewire:datatable model="App\User" />
`

**Comment by EmmanuelAyTuz** [comment]
Thanks for your ideas.
