### ISSUE TITLE
conflict composer require on php 8 

### ISSUE THREAD

**Issue by masbenx** [EmmanuelAyTuz/Views-BS4-Livewire-Datatable#14]
when I using PHP 8, the livewire datatable composer version is using "dev-master". but your composer require is "0.4.3". 

the problem is when installing this package show error :

`Problem 1
    - Root composer.json requires emmanuel/livewire-datatable-bs4 dev-main -> satisfiable by emmanuel/livewire-datatable-bs4[dev-main].
    - emmanuel/livewire-datatable-bs4 dev-main requires mediconesystems/livewire-datatables ^0.4.3 -> found mediconesystems/livewire-datatables[v0.4.3] but it conflicts with your root composer.json require (dev-master).`

**Comment by MACscr** [comment]
anyone get around this?

**Comment by EmmanuelAyTuz** [comment]
> anyone get around this?

Sorry for the long time without reviewing this issue.

This issue has been fixed, adding "|" in the composer.json with version "dev-master" of "mediconesystems/livewire-datatables"
Thank you.

------php info------
PHP 8.0.6 (cli) (built: May  4 2021 23:31:45) ( ZTS Visual C++ 2019 x64 )
Copyright (c) The PHP Group
Zend Engine v4.0.6, Copyright (c) Zend Technologies

**Comment by muhammedshiffin** [comment]
> > anyone get around this?
> 
> Sorry for the long time without reviewing this issue.
> 
> This issue has been fixed, adding "|" in the composer.json with version "dev-master" of "mediconesystems/livewire-datatables"
> Thank you.
> 
> ------php info------
> PHP 8.0.6 (cli) (built: May 4 2021 23:31:45) ( ZTS Visual C++ 2019 x64 )
> Copyright (c) The PHP Group
> Zend Engine v4.0.6, Copyright (c) Zend Technologies

What exactly do we need to do ?

**Comment by EmmanuelAyTuz** [comment]
> > > anyone get around this?
> > 
> > 
> > Sorry for the long time without reviewing this issue.
> > This issue has been fixed, adding "|" in the composer.json with version "dev-master" of "mediconesystems/livewire-datatables"
> > Thank you.
> > ------php info------
> > PHP 8.0.6 (cli) (built: May 4 2021 23:31:45) ( ZTS Visual C++ 2019 x64 )
> > Copyright (c) The PHP Group
> > Zend Engine v4.0.6, Copyright (c) Zend Technologies
> 
> What exactly do we need to do ?

The up actions only is the description

Just use composer require emmanuel/livewire-datatable-bs4

And publish the files php artisan vendor:publish --tag="livewire-datatable-bs4"

Do you have other problems? I would like to know

**Comment by muhammedshiffin** [comment]
> > > > anyone get around this?
> > > 
> > > 
> > > Sorry for the long time without reviewing this issue.
> > > This issue has been fixed, adding "|" in the composer.json with version "dev-master" of "mediconesystems/livewire-datatables"
> > > Thank you.
> > > ------php info------
> > > PHP 8.0.6 (cli) (built: May 4 2021 23:31:45) ( ZTS Visual C++ 2019 x64 )
> > > Copyright (c) The PHP Group
> > > Zend Engine v4.0.6, Copyright (c) Zend Technologies
> > 
> > 
> > What exactly do we need to do ?
> 
> The up actions only is the description
> 
> Just use composer require emmanuel/livewire-datatable-bs4
> 
> And publish the files php artisan vendor:publish --tag="livewire-datatable-bs4"
> 
> Do you have other problems? I would like to know

I mean, am facing the same issue while installing it via composer

 Problem 1
    - Root composer.json requires emmanuel/livewire-datatable-bs4 dev-main -> satisfiable by emmanuel/livewire-datatable-bs4[dev-main].
    - emmanuel/livewire-datatable-bs4 dev-main requires mediconesystems/livewire-datatables ^0.4.3|dev-master -> found mediconesystems/livewire-datatables[dev-master, v0.4.3] but the package is fixed to v0.5.4 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.

This is with version 0.5.4 of livewire-datatables

**Comment by EmmanuelAyTuz** [comment]
> 0.5.4

Thanks for you report, I'll add the version 0.5.4 in the composer.json, check please ...

**Comment by muhammedshiffin** [comment]
> > 0.5.4
> 
> Thanks for you report, I'll add the version 0.5.4 in the composer.json, check please ...

Sure, I will check once you update it. Thanks Mate..!
