### ISSUE TITLE
Version Livewire Datatable v0.5.4

### ISSUE THREAD

**Issue by EmmanuelAyTuz** [EmmanuelAyTuz/Views-BS4-Livewire-Datatable#19]
@muhammedshiffin

**Comment by muhammedshiffin** [comment]
thanks Mate, eagerly waiting for the update ! Cheers..

**Comment by EmmanuelAyTuz** [comment]
> thanks Mate, eagerly waiting for the update ! Cheers..

Thanks, I´m checking https://github.com/MedicOneSystems/livewire-datatables for the updates and changes, first commits in Package branch --> Main branch

**Comment by muhammedshiffin** [comment]
> > thanks Mate, eagerly waiting for the update ! Cheers..
> 
> Thanks, I´m checking https://github.com/MedicOneSystems/livewire-datatables for the updates and changes, first commits in Package branch --> Main branch

The package seems to work fine now ! Thanks & Cheers

**Comment by EmmanuelAyTuz** [comment]
> > > thanks Mate, eagerly waiting for the update ! Cheers..
> > 
> > 
> > Thanks, I´m checking https://github.com/MedicOneSystems/livewire-datatables for the updates and changes, first commits in Package branch --> Main branch
> 
> The package seems to work fine now ! Thanks & Cheers

Sorry for the reply time and I'll close the issue but I'm checking the features and changes of Livewire Datatable by MedicOneSystems, thanks.
