### ISSUE TITLE
Example of use

### ISSUE THREAD

**Issue by joaonivaldo** [EmmanuelAyTuz/Views-BS4-Livewire-Datatable#2]
Hello, I'm having some difficulties using this version of your Data Table. He is not showing the headings of the table or the research line. Do you happen to have a working example using these templates for me to see? Thanks
![livewire-datatalble-error-01](https://user-images.githubusercontent.com/4040086/114476456-a2194500-9bd0-11eb-8479-ca85853ae95a.jpg)

**Comment by EmmanuelAyTuz** [comment]
Thanks for your ideas, you need fontawesome.
Do you use template? adminlte, jetstrap, etc, mmm check.

**Comment by joaonivaldo** [comment]
use the ADMINLTE and JETSTRAP with fontawesome 5.

Look, I updated my project with your corrections and really now the header line has appeared. and formatted everything just right. Only the search line that is above the header line does not appear. Only a gray block appears in place. Thanks
![image](https://user-images.githubusercontent.com/4040086/114919763-07eb1400-9dff-11eb-9322-9835e75f2e38.png)

**Comment by EmmanuelAyTuz** [comment]
This gray block is simple pagination but the icon isn´t working and only the button appears, if you need the search field you have two ways:
 - Template syntax: <livewire:datatable model="App\Models\User" searchable="**name,emai**l" />
 - Component Syntax: add ->_searchable()_

And last update your packages "**composer update**" and "**npm install**". Try
![image](https://user-images.githubusercontent.com/34067768/114971985-1c510000-9e43-11eb-9ec3-14f85f9569f9.png)

**Comment by hemant17** [comment]
Kind of same for me when i install it first time it's show me blank header

**Comment by EmmanuelAyTuz** [comment]
> Kind of same for me when i install it first time it's show me blank header

This bug has been fixed but if you've a new bug I would like to give me more info

This bug has been fixed, but if you have a new bug, I'd like to get more information.

**Comment by EmmanuelAyTuz** [comment]
> Kind of same for me when i install it first time it's show me blank header

This bug has been fixed, but if you have a new bug, I'd like more information.

**Comment by joaonivaldo** [comment]
it was really just adding the model that the search bar appeared. Now only the simple navigation bar is not showing the icons. Do you have to install an icon library or something? Another thing is how to translate the package to pt-BR? Thanks for your help.
![image](https://user-images.githubusercontent.com/4040086/115238020-960f1500-a0f3-11eb-9e2d-83fb2ea87cb9.png)

**Comment by EmmanuelAyTuz** [comment]
> it was really just adding the model that the search bar appeared. Now only the simple navigation bar is not showing the icons. Do you have to install an icon library or something? Another thing is how to translate the package to pt-BR? Thanks for your help.
> ![image](https://user-images.githubusercontent.com/4040086/115238020-960f1500-a0f3-11eb-9e2d-83fb2ea87cb9.png)

Would you share the package.json and composer.json?

**Comment by EmmanuelAyTuz** [comment]
> it was really just adding the model that the search bar appeared. Now only the simple navigation bar is not showing the icons. Do you have to install an icon library or something? Another thing is how to translate the package to pt-BR? Thanks for your help.
> ![image](https://user-images.githubusercontent.com/4040086/115238020-960f1500-a0f3-11eb-9e2d-83fb2ea87cb9.png)

Check issue #4 : if you want to try this, check out the 'idea-one-tr' branch and tell me.

**Comment by EmmanuelAyTuz** [comment]
> it was really just adding the model that the search bar appeared. Now only the simple navigation bar is not showing the icons. Do you have to install an icon library or something? Another thing is how to translate the package to pt-BR? Thanks for your help.
> ![image](https://user-images.githubusercontent.com/4040086/115238020-960f1500-a0f3-11eb-9e2d-83fb2ea87cb9.png)

I'm working in a single package with translations in english, spanish & pt-br for this moment, check 'package' branch, Thanks for you ideas and recomendations.
