### ISSUE TITLE
Conflict with newest version of mediconesystems/livewire-datatables

### ISSUE THREAD

**Issue by emageint** [EmmanuelAyTuz/Views-BS4-Livewire-Datatable#24]

**Comment by EmmanuelAyTuz** [comment]
Could you give me a screenshot or the text log?

**Comment by emageint** [comment]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires emmanuel/livewire-datatable-bs4 dev-main -> satisfiable by emmanuel/livewire-datatable-bs4[dev-main].
    - emmanuel/livewire-datatable-bs4 dev-main requires league/flysystem 1.1.4 -> found league/flysystem[1.1.4] but the package is fixed to 1.1.5 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the u
pdate command.

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

**Comment by invaders-xx** [comment]
Hello,

I am facing the same issue:

Problem 1
    - Root composer.json requires emmanuel/livewire-datatable-bs4 dev-main -> satisfiable by emmanuel/livewire-datatable-bs4[dev-main].
    - emmanuel/livewire-datatable-bs4 dev-main requires league/flysystem 1.1.4 -> found league/flysystem[1.1.4] but the package is fixed to 1.1.5 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    -

**Comment by EmmanuelAyTuz** [comment]
Ohhh no, thanks for you report-issue.
I'll be checking this error ASAP
The initial commits start in package-features branch and write me a comment on this open-issue

**Comment by invaders-xx** [comment]
I installed "emmanuel/livewire-datatable-bs4": "dev-package" without any issue but I have the following error when trying to load a view:
"Undefined variable $table (View: ....resources/views/livewire/datatables/editable.blade.php) "

**Comment by EmmanuelAyTuz** [comment]
> I installed "emmanuel/livewire-datatable-bs4": "dev-package" without any issue but I have the following error when trying to load a view: "Undefined variable $table (View: ....resources/views/livewire/datatables/editable.blade.php) "

Mmm, a quick check has apparently changed to $key

Thanks for sending your report, I'll be checking this error ASAP

(Sorry for edit your comment, I didn't see that I was editing) 😅

**Comment by EmmanuelAyTuz** [comment]
Thanks for report the issue and test the new changes.
And if you have a new issue, give a new open-issue
