### ISSUE TITLE
Modal for Delete not Working

### ISSUE THREAD

**Issue by phennom2000** [EmmanuelAyTuz/Views-BS4-Livewire-Datatable#3]
Hi, first of all , thanks for your work on this. I greatly appreciate what you have done.
My Modal for delete is not working, when using Column::delete()->label('delete')

**Comment by EmmanuelAyTuz** [comment]
What is the identifier of your table?
The delete() must have a parameter $name='id', if your table doesn't have the field, you can override it with delete('field_id').
Check

**Comment by phennom2000** [comment]
thanks for your fast reply. the ID field is present in my table NumberColumn::name('id')->filterable()  .
I will check it later again

**Comment by EmmanuelAyTuz** [comment]
Test override 👍

**Comment by phennom2000** [comment]
I fixed it by creating my own modal with the callback function. 
( You saved me a lot of work with this Boostrap version )
