### ISSUE TITLE
2 TR in threadhead when using default 

### ISSUE THREAD

**Issue by hemant17** [EmmanuelAyTuz/Views-BS4-Livewire-Datatable#4]
![image](https://user-images.githubusercontent.com/10548023/115137145-e332ae80-a041-11eb-8aea-8667ad4ed33a.png)
![image](https://user-images.githubusercontent.com/10548023/115137151-f5145180-a041-11eb-829e-e07b64a80267.png)
Extra TR on default table 
might be you using 2 TR and leave one blank. 
```<livewire:datatable model="App\User" include="id,name,email,phone" />

**Comment by EmmanuelAyTuz** [comment]
Thanks for your recommendations, it's been merged into a single TR, if you want to try this, check out the 'idea-one-tr' branch and tell me.
![image](https://user-images.githubusercontent.com/34067768/115183750-11e07180-a0a2-11eb-97d8-877fe0ec414f.png)
![image](https://user-images.githubusercontent.com/34067768/115183855-405e4c80-a0a2-11eb-993a-f9d540968c07.png)


![image](https://user-images.githubusercontent.com/34067768/115183899-51a75900-a0a2-11eb-827f-80c33c20b4d8.png)
![image](https://user-images.githubusercontent.com/34067768/115184002-86b3ab80-a0a2-11eb-83c9-9a34938523e2.png)

**Comment by hemant17** [comment]
Look good :)  👍 
one more thing when you merge just add pl-0 and w-100 on the button so the whole button area will be clickable and  the text-align with the Tbody row

![image](https://user-images.githubusercontent.com/10548023/115192675-c01f0200-a108-11eb-8cda-eb677e2e62e3.png)
try from your end also in long table
